### PR TITLE
Add a simple logo animation

### PR DESCRIPTION
**Pull request by relu91**
While working for the WoT farm sim, I needed a nice splash screen to cover the loading process. I created this animation of WoT logo. It might be useful for other WoT applications or videos, so I'm uploading it in this repo. You can preview it in the readme of this PR. The animation is available both in gif and HTML format. 

Feel free to close this PR if it is not needed.

### CODE REVIEW

**Comment by danielpeintner** [comment]
Looks nice.
Let's discuss in the marketing call how to proceed and where to use the animation...

**Comment by egekorkan** [comment]
I really like this! One little variation could be moving the temperature marker high or low and changing the color of the T accordingly. Could be interesting but it is already really nice :)

**Comment by relu91** [comment]
I was wondering is there something that holds on this issue? Or we just need to discuss it in a call?

**Comment by danielpeintner** [comment]
Good question. I think it is definitively worth merging... not sure whether we want to quickly discuss it in the call..

**Comment by sebastiankb** [comment]
based on today's marketing call we decided to merge this PR. 
Thanks @relu91

**Comment by relu91** [comment]
Thanks for merging and apologies for skipping the call today.

**Pull request merged**
