### PR TITLE
add AASX Package Explorer tool

### PR DESCRIPTION
**Pull request by sebastiankb**
add AASX Package Explorer tool to the developer list

### CODE REVIEW

**Comment by egekorkan** [comment]
I would prefer to put the release link which is more recent than the linked action

**Comment by egekorkan** [comment]
Call of 18.01:
We want to point to a generic link like https://admin-shell-io.com/ or https://github.com/admin-shell-io/aasx-package-explorer . The link in the PR points to a GitHub action and pointing to a specific release would become outdated quickly. Thus, a generic link is needed so that we do not need to maintain it constantly. @sebastiankb Could you use one of the links above?

**Comment by sebastiankb** [comment]
just updated the link

**Review by egekorkan — APPROVED** [review]

**Comment by danielpeintner** [comment]
I noticed the `a` tag should have used `target="_blank"` to open the link in a new tab/window.

**Pull request merged**
