### PR TITLE
add video thumbnail

### PR DESCRIPTION
**Pull request by danielpeintner**

### CODE REVIEW

**Comment by danielpeintner** [comment]
Note: I played a bit around but it is very difficult to mock-up the twitter text style etc.

Does anyone have another proposal where to put the thumbnail that is meant to  point to a video page.

grafik

**Comment by relu91** [comment]
It looks ok, although I feel that the Twitter timeline is a little bit too short... I mean it can display just one tweet. Can we make the page a little taller and move the video to the right of the description?. Something like this:

image

**Comment by danielpeintner** [comment]
> It looks ok, although I feel that the Twitter timeline is a little bit too short... I mean it can display just one tweet. Can we make the page a little taller and move the video to the right of the description?. Something like this:

@relu91 I like your proposal! Will try that out

**Comment by egekorkan** [comment]
I also like @relu91 proposal. The video is new and very presentable so it would be nice to promote it as much as possible :)

**Comment by danielpeintner** [comment]
I integrated the changes. It might look even better if the intro para is longer too (or maybe talks/links the video also).

grafik

**Comment by danielpeintner** [comment]
The alternative would be to move the header next to the video thumbnail

grafik

**Comment by sebastiankb** [comment]
+1 for the last version

**Comment by sebastiankb** [comment]
After the sentence "... across IoT platforms and application domains. " would be good to have a new paragraph with the sentence "Get more background about Web of Things [here](https://w3c.github.io/wot-marketing/documentation/)".

**Comment by danielpeintner** [comment]
> After the sentence "... across IoT platforms and application domains. " would be good to have a new paragraph with the sentence "Get more background about Web of Things [here](https://w3c.github.io/wot-marketing/documentation/)".

Makes sense. I slightly updated the text to make the link a proper description for the link which is better than "here" for search engines.

Get more background about Web of Things in the [Documentation](#) area.

**Pull request merged**
