### PR TITLE
Update UI

### PR DESCRIPTION
**Pull request by danielpeintner**
* new navigation with activities
* ~~inverted logo~~

### CODE REVIEW

**Comment by danielpeintner** [comment]
grafik

**Comment by egekorkan** [comment]
I was actually in favor of inverting the logo but it now looks a bit weird to me 🙈 Maybe a light grey for the inside suit better? What do the others think?

**Comment by danielpeintner** [comment]
FYI: I removed the inverted logo for the time being as discussed in marketing call.

Idea: move logos (WoT and W3C) above navigation bar

**Comment by sebastiankb** [comment]
as discussed today. Other change request will be provided in different PRs

**Pull request merged**
