### PR TITLE
Updates events with Developer Meeting, March 2023

### PR DESCRIPTION
**Pull request by danielpeintner**
fixes https://github.com/w3c/wot-marketing/issues/376
fixes https://github.com/w3c/wot-marketing/issues/373

### CODE REVIEW

**Comment by danielpeintner** [comment]
Note: what else could be added?

**Comment by egekorkan** [comment]
@danielpeintner also https://github.com/w3c/wot-marketing/issues/373 (https://iiwot22.nws.cs.unibo.it/)

**Comment by danielpeintner** [comment]
I added IEEE IIWOT 2023, I think the link provided points to last years event. 
Hence, I used https://iiwot23.nws.cs.unibo.it/

**Comment by egekorkan** [comment]
@danielpeintner could you move IIWOT to past events?

Regarding netlify, I do not know what is going on but it does not work anywhere atm.

**Comment by danielpeintner** [comment]
> @danielpeintner could you move IIWOT to past events?

My bad, fixed it with https://github.com/w3c/wot-marketing/pull/377/commits/6a7a520a04e6b8eb9e72aa387e4c7c348ac25794

**Review by egekorkan — APPROVED** [review]

**Pull request merged**
