### PR TITLE
Webpage: Adding TF info to WG and IG overview pages

### PR DESCRIPTION
**Pull request by mlagally**
This change simplifies navigation and gives credit to TF leads.

### CODE REVIEW

**Review by danielpeintner — COMMENTED** [review]
I am not all opposed to it.
I just wonder whether it is _simpler_ to point to the *general* task force page only.

Moreover, I would have difficulties to draw the line which task-force belongs to WG, IG, or both.

**Comment by ashimura** [comment]
I thought I had given my comment yesterday but apparently forgot to push the "Comment" button :)

---
I also think clarifying the affiliation of each TF would be useful and important, because:

1. Technically, the WoT WG and the WoT IG are different groups run on their own Charters,

2. Some of the group participants participate in only one of the two groups, and

3. We should provide information about which group works on what topics so that people can choose which group to join easily.

Please note that when I mentioned "New WoT WG page should be upper-compatible to the current one" in my issue #84, I meant the WG page should clearly state which work items belong to the WG.

The basic scopes of the WoT WG and the WoT IG are defined by the [WoT WG Charter](https://www.w3.org/2020/01/wot-wg-charter.html) and the [WoT IG Charter](https://www.w3.org/2016/07/wot-ig-charter.html) respectively. Also our wiki pages identify which TF belongs to which group (or joint work). So we can clarify which TF belongs to which group (or both the groups).

Regarding the style of the content, I'm OK with cross-referencing from the Group page to the TF page and from the TF page to the Group page, and we can talk about it during the upcoming WoT Marketing calls.

**Review by sebastiankb — APPROVED** [review]

**Comment by danielpeintner** [comment]
w.r.t. the content I think it is fine. I would suggest some *visual* fine-tuning:
* Move task forces tables "below" the Charter, mailing list etc links... right before the publication status
* The newly added tables seem to be squeezed a bit. I would suggest to add some spacing between the columns

Both points can be addressed (also by me) after merging ...


grafik

**Comment by sebastiankb** [comment]
based on yesterday's main call, it was decided to merge this PR.

**Pull request merged**
