### PR TITLE
Proposal for TF pages

### PR DESCRIPTION
**Pull request by egekorkan**
Was proposed in the TD Meeting of 25.11.2020

### CODE REVIEW

**Comment by mmccool** [comment]
So in parallel to this PR I created another PR that filled in content for three task forces (Security, Architecture, and Discovery) following from material put together in the Architecture call today.  This does not follow this template exactly, for instance I don't repeat the call-in information since it is on (or should be) on the wiki page.   I also add links to the github sites for each TF because that is generally where the interesting technical content is (and also posting issues is a way for people to provide input...)

I also listed all the people acting as chairs or editors in each TF.

See https://github.com/w3c/wot-marketing/pull/100

Still good to have a template, and I 100% agree that we need to get each TF description to look consistent, but we'll have to update either the template or the content in the other PR to get there.

**Comment by mlagally** [comment]
I very much support the proposed draft done by Michael McCool in https://github.com/w3c/wot-marketing/pull/100

**Comment by danielpeintner** [comment]
@sebastiankb  @egekorkan can you provide a PR for TD/binding task force? 

Note: in scripting the current proposal is aligned with https://github.com/w3c/wot-marketing/pull/100. All might use the same?

**Comment by egekorkan** [comment]
Given that #100 is more appreciated, I am closing this PR

**Comment by egekorkan** [comment]
@danielpeintner I am not sure if you asked for two or one document. @sebastiankb is the binding templates its own task force or is it simply a deliverable by the TD TF?

**Comment by danielpeintner** [comment]
> @danielpeintner I am not sure if you asked for two or one document. @sebastiankb is the binding templates its own task force or is it simply a deliverable by the TD TF? I was just writing the intro and couldn't be sure

Good question. My take is that given it is also in the same call it is _one_ task force but I guess this is something we need to decide.

**Pull request closed without merging**
