### PR TITLE
Add edit page button on all pages

### PR DESCRIPTION
**Pull request by egekorkan**
I have added some negative margins so that the new text doesn't push the page further down. Not sure if this is best practice

### CODE REVIEW

**Comment by egekorkan** [comment]
Call of 05.04:
- We should rename it to something like "Suggest Changes" since they cannot directly edit it
- A small button (like a folded page) on the top left or right would be visually better
- We should clarify our policy first, i.e. do we accept PRs from anyone or only WG IG members etc.

**Comment by egekorkan** [comment]
@relu91 I have found the following: https://tholman.com/github-corners/

**Comment by egekorkan** [comment]
I think the new button is less visible but nicer looking, which is a win-win given the criticism:
- It just points to the page at GitHub and nothing more, thus there is no implication about editing or even suggesting changes.
- Looks neat
- There is a small animation. It can be removed easily

**Comment by danielpeintner** [comment]
Note: I tried to look at it on mobile and there Github Logo  and W3C logos are overlapping.

**Comment by egekorkan** [comment]
hmm true and it would overlap with the WoT logo if put on the left. Doing it somewhere else might look weird, I will quickly check

**Comment by relu91** [comment]
That's great! +1 for the corner. Minor remarks, I think using a shade of blue blends a little bit better with the current site style:
image

About mobile, I would simply hide the button using a CSS media query. Editing the page on mobile is not really practical anyway...

**Review by relu91 — APPROVED** [review]

**Review by danielpeintner — APPROVED** [review]

**Pull request merged**
