### PR TITLE
Add Eclipse ditto based tools

### PR DESCRIPTION
**Pull request by egekorkan**
@thjaeckle I cannot add you as a reviewer but it would be nice if you can have a look. I have tried to describe ditto WoT integration in a concise way but may not be very accurate. Please ignore the categorization for now since the outcome of #245 will change that

### CODE REVIEW

**Review by thjaeckle — COMMENTED** [review]
Please write Ditto with capital D. 
So: "Eclipse Ditto" on first occurance and eg "Ditto" later.

I would e.g. suggest for the brief description:
Ditto managed digital twins can be linked to WoT Thing Models from which Ditto can create Thing Descriptions containing the API descriptions of the twins.

**Comment by egekorkan** [comment]
@thjaeckle I have incorporated your feedback

**Review by thjaeckle — APPROVED** [review]
Looks good to me :+1:
Thank you for adding it to the page.

**Comment by danielpeintner** [comment]
Not an issue of this change only... but maybe wen can add a colon or a " - " after the url link or so to better separate the text

grafik

> [WoT Integration for Eclipse Ditto](https://www.eclipse.org/ditto/basic-wot-integration.html) Ditto managed digital ...

To me it looks a bit strange to have "Ditto" twice in the text.
The same applies for AASX

**Comment by egekorkan** [comment]
The fixes for the last comment will be done at https://github.com/w3c/wot-marketing/issues/280

**Pull request merged**
