### PR TITLE
refactor: replace flaticons with fontawesome

### PR DESCRIPTION
**Pull request by danielpeintner**
fixes https://github.com/w3c/wot-marketing/issues/238

### CODE REVIEW

**Comment by danielpeintner** [comment]
different look and feel, see examples below

## --> homepage

grafik


## --> wg site

grafik

**Comment by egekorkan** [comment]
I like them except for the CG logo that is apparently the sign language interpretation. Saying that, I couldn't find a very good alternative but here are some that I thought that can be related (I have looked at all the free icons and everything seems relatable at some point after desperation...)
- grafik at https://fontawesome.com/v5.9/icons/hands-helping?style=solid
- grafik at https://fontawesome.com/v5.9/icons/handshake?style=solid
- grafik at https://fontawesome.com/v5.9/icons/shapes?style=solid , like building something together
- grafik at https://fontawesome.com/v5.9/icons/poll?style=solid like community that votes and hears opinions
- grafik
 at https://fontawesome.com/v5.9/icons/coffee?style=solid like meeting around a coffee
- grafik
 at https://fontawesome.com/v5.9/icons/comments?style=solid like a community that listens to comments

**Comment by danielpeintner** [comment]
I agree, the CG should use  a more appropriate icon for the CG and I like the "comments" icon most. What do you think?

## Screenshot

grafik

**Comment by danielpeintner** [comment]
Note: I think we can easily change the icons in the future if we feel unconformable with them.
Having said that, right now the website looks somewhat strange without *any* icons and I encourage to merge the PR soon 🙃

**Comment by egekorkan** [comment]
I like this icon and would say that we can merge it in the next call.

**Review by egekorkan — APPROVED** [review]

**Pull request merged**
