### PR TITLE
Trying different Twitter/X integration

### PR DESCRIPTION
**Pull request by egekorkan**
A single post works when given the specific link but a timeline does not work nor do we have an automatic way to get the latest tweet. We can keep updating this manually, remove the embed and link to the account or remove it entirely.

### CODE REVIEW

**Comment by danielpeintner** [comment]
> We can keep updating this manually, remove the embed and link to the account or remove it entirely.

Since we are not posting that often this might work but is far from ideal

**Comment by egekorkan** [comment]
Really weird but it works on my phone's Chrome browser but not on Firefox

**Comment by danielpeintner** [comment]
> Really weird but it works on my phone's Chrome browser but not on Firefox

I have the exact same situation...
Having said that, I think we cannot do much about it. Let's hope it gets settled somehow. I think we can just wait and monitor the situation.

**Comment by egekorkan** [comment]
In today's main call, the group's opinion was to go with this PR. Merging now.

**Comment by danielpeintner** [comment]
Note: How could we setup a regular reminder to check for a *new* tweet?

**Comment by egekorkan** [comment]
> Note: How could we setup a regular reminder to check for a _new_ tweet?

I think it should be a permanent agenda of the marketing calls.

**Pull request merged**
