### PR TITLE
Adding a template for CG groups

### LINKED ISSUE #237: Updating the CG templates
In the call of 11.01.2021, we have agreed to reduce redundancy and keep only the CG name, a paragraph of description and link to their homepage in our WoT pages.

https://github.com/w3c/wot-marketing/blob/main/docs/cg/index.html needs to be updated and a small template in HTML needs to be created to be sent to CG to send their information.

### PR DESCRIPTION
**Pull request by egekorkan**
Fixes #237

### CODE REVIEW

**Review by danielpeintner — COMMENTED** [review]
Are the changes in docs/cg/index.html intentional ?
This causes a lot of noise ... are there really any changes in this file?

Applying these changes may also conflict with the PR about flaticons...

**Comment by egekorkan** [comment]
It was intentional since I wanted to provide the template with the same structure. I have just formatted it via prettier. 
Regarding flaticons PR, I would merge that one first and adapt this one accordingly.

**Comment by egekorkan** [comment]
Call of 18.01: @egekorkan will resolve the merge conflicts in an editor offline however the group has agreed on the change

**Comment by egekorkan** [comment]
I have also added gemfile in case people need to use bundler (I had to due to some windows problems). It is also needed for generating static content

**Comment by egekorkan** [comment]
@danielpeintner can you have a final look? Since the content is agreed upon, we can merge it without a meeting

**Review by danielpeintner — COMMENTED** [review]
Content-wise it looks good.

I wonder *why* you added the GEMFILES. In my case I had to remove both files to make `jekyll serve` work again on my windows machine.. (see error log below)

If there is no strong reason for having those files (and if it used to work before) I suggest to remove them again.


```
Traceback (most recent call last):
        19: from C:/Ruby26-x64/bin/jekyll:23:in `<main>'
        18: from C:/Ruby26-x64/bin/jekyll:23:in `load'
        17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/exe/jekyll:11:in `<top (required)>'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler.rb:107:in `setup'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:20:in `setup'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:108:in `block in definition_method'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/definition.rb:226:in `requested_specs'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/definition.rb:237:in `specs_for'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/definition.rb:170:in `specs'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/definition.rb:258:in `resolve'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/resolver.rb:22:in `resolve'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/resolver.rb:50:in `start'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb:43:in `resolve'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:182:in `resolve'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:257:in `process_topmost_state'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:308:in `tap'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:328:in `raise_error_unless_state': Unable to satisfy the following requirements: (Bundler::Molinillo::VersionConflict)

- `ffi (= 1.15.5) x64-unknown` required by `Gemfile.lock`
- `ffi (~> 1.9) x64-mingw32` required by `sassc (2.4.0)`
        13: from C:/Ruby26-x64/bin/jekyll:23:in `<main>'
        12: from C:/Ruby26-x64/bin/jekyll:23:in `load'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/exe/jekyll:11:in `<top (required)>'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler.rb:107:in `setup'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:20:in `setup'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:108:in `block in definition_method'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/definition.rb:226:in `requested_specs'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/definition.rb:237:in `specs_for'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/definition.rb:170:in `specs'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/definition.rb:258:in `resolve'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/resolver.rb:22:in `resolve'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/resolver.rb:45:in `start'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/resolver.rb:56:in `rescue in start': Bundler could not find compatible versions for gem "ffi": (Bundler::VersionConflict)
  In snapshot (Gemfile.lock):
    ffi (= 1.15.5)

  In Gemfile:
    jekyll (~> 4.2) x64-mingw32 was resolved to 4.2.1, which depends on
      jekyll-sass-converter (~> 2.0) x64-mingw32 was resolved to 2.1.0, which depends on
        sassc (> 2.0.1, < 3.0) x64-mingw32 was resolved to 2.4.0, which depends on
          ffi (~> 1.9) x64-mingw32

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by egekorkan** [comment]
Well the getting started guide for Jekyll uses `bundle` and it is even required for ruby > 3.0 . See https://jekyllrb.com/docs/ 

Both commands work for me but I need the Gemfile for sure. Can you try again by upgrading to Ruby 3.0 ?

**Comment by danielpeintner** [comment]
I updated Ruby (3.0.3-1) and Jekyll (4.2.1).
Different error. 😒

I finally figured it out. The **IMPORTANT** information is on https://jekyllrb.com/docs/step-by-step/10-deployment/
Using Gemfiles needs a different way of running the commands.

1. `bundle install` needs to be called first
2. `bundle exec jekyll serve` to test (it used to be `jekyll serve` only)

Having said that, IF we use Gemfiles we also need to update the documentation on
https://github.com/w3c/wot-marketing/tree/main/docs#testing-site-locally-with-jekyll

Note: I hope the rendering process on GitHub works with Gemfiles as expected.

**Comment by egekorkan** [comment]
So I have looked at what GitHub says and they also recommend using bundler and gemfiles: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll

I have now tried in three different installations, 2 windows and 1 linux. Only in 1 windows I cannot get jekyll to work without bundler. In all cases, bundler version works.

Given that GitHub also recommends bundler, I say we go with it and see if the rendering works as usual. If the process breaks, we can revert the PR. I can also move this to another PR.

**Comment by danielpeintner** [comment]
I am OK with proceeding with Gemfiles and this PR. Anyhow, we should update the readme before merging this PR as mentioned before.

> Having said that, IF we use Gemfiles we also need to update the documentation on
> https://github.com/w3c/wot-marketing/tree/main/docs#testing-site-locally-with-jekyll

**Comment by egekorkan** [comment]
@danielpeintner please see #254

**Pull request merged**
