### PR TITLE
Align all thumbnails by downloading from the thumbnail page

### PR DESCRIPTION
**Pull request by egekorkan**
This is a first try to align the thumbnails but so far unsuccessful... There are the following issues:
- Not all videos have the maxresolution URL and only an "HQ" resolution that is actually really low resolution.
- Not all thumbnails have the same proportions, which results in black bars around them and that is sometimes up and bottom, sometimes left and right.

### CODE REVIEW

**Comment by egekorkan** [comment]
Call of 13.06: @egekorkan will try https://chrome.google.com/webstore/detail/screenshot-youtube/gjoijpfmdhbjkkgnmahganhoinjjpohk

**Comment by egekorkan** [comment]
The screenshot tool works but it is still not 100% what I want... Some videos like the ASC2020 and the Workshop at Siemens have thumbnail pictures that are not a screenshot of the video. I guess those will have to stay thumbnails.

**Comment by egekorkan** [comment]
I have done the necessary changes. Please do not use the Netlify PR Preview to view the PR since it is loading the images from the w3.org.

**Review by danielpeintner — APPROVED** [review]
LGTM

Documenting the procedure seems useful 👍

**Comment by egekorkan** [comment]
Call of 27.06: In the end we have a dependency to an extension but the process is very straightforward that one can even write a script to extract the image.

**Pull request merged**
