### PR TITLE
Swap security and discovery call slots

### LINKED ISSUE #452: Update schedule for Discovery and Security
https://lists.w3.org/Archives/Member/member-wot-wg/2023Nov/0005.html

> The WoT Security call occurs at 3-4pm CET while the WoT Discovery call move to 2-3pm CET.

### PR DESCRIPTION
**Pull request by egekorkan**
fixes #452

### CODE REVIEW

**Comment by danielpeintner** [comment]
I think we need to move it "before" ... discovery starts right after scripting 

image

**Comment by egekorkan** [comment]
It is fixed now: https://deploy-preview-453--wot-marketing.netlify.app/activities/meetings/

**Comment by danielpeintner** [comment]
> It is fixed now: https://deploy-preview-453--wot-marketing.netlify.app/activities/meetings/

I think it is still wrong... security has to move as well.
I think on Monday we have three hours in a row...

**Comment by egekorkan** [comment]
The shown times are correct but the wrong timezone is displayed. A separate PR will correct that.

**Pull request merged**
