### PR TITLE
Add new tool organization

### PR DESCRIPTION
**Pull request by egekorkan**
I have added a category matrix and a table of tools with the features they cover. This is a draft and not intended to be the final look of the page, the table is very basic for sure. My opinions:
- Doing a table of features blows up the table horizontally. I can reduce the granularity.
- Doing a table was nice to see what features are implemented in which tool. I did it with my knowledge and not looking into tools' source codes.
- It is annoying to assign some projects to a single category and table works better in those cases.

- I think that listing the features is nice but a table like this is not a good design or visualization method. It is too high/long (we cannot do anything about that) and too wide (can be simplified)

Looking forward to what people think

### CODE REVIEW

**Comment by egekorkan** [comment]
Also, I need to add links from each tool in the table to their description.

**Comment by danielpeintner** [comment]
I agree, the table is not very UI friendly.. also w.r.t. mobile devices in mind.

**Comment by egekorkan** [comment]
A way to include the information of the table would be to put the supported features under each tool, a bit like tags

**Comment by danielpeintner** [comment]
> A way to include the information of the table would be to put the supported features under each tool, a bit like tags

I like the idea.. having badges next to each implementation.

**Comment by egekorkan** [comment]
I did not have time to put the tags next to each tool but I have commented out the table for now so that we can merge it. I will add the icons/tags in a subsequent PR

**Comment by egekorkan** [comment]
Call of 03.05:
@mmccool mentions that we should not have long sentences under the icons and their titles. Proposal is to move these sentences to the parts below. @egekorkan will edit the PR

**Comment by egekorkan** [comment]
call of 10.05:
- Development Tools is a bit vague, @egekorkan will put further specific words 
- dot is missing at the end of the descriptions
- TD tooling has wrong descrpition
These points will be fixed and this PR will me merged asynchronously. A followup PR is needed to provide the features of each tool, see : https://github.com/w3c/wot-marketing/pull/309#issuecomment-1104792543

**Pull request merged**
