### PR TITLE
fix duplication in subtitles

### LINKED ISSUE #150: Imprecise Subtitles for WoT Explainer Video
During the subtitle translation work #149, I spotted a few problems in the source subtitle file:

- The timing of the subtitles are not precise. Worse, some subtitles overlap, e.g. 00:31, 02:23.
- There might be some typos / mistakes, e.g.:
  - 00:26 "_They_ would like..." in the subtitle is "_He_ would like..." in the voice.
  - 00:59 "WoT is a _W3C_ standard..." in the subtitle is "WoT is a _W3_ standard..." in the voice.
  - 02:32 "_TD_ like identification, ..." in the subtitle is "... like identification, ..." in the voice.

For the translated subtitle in #149:

- Timing is not fixed. It needs to be updated for all languages at once.
- _Some_ typos / mistakes are not reflected, while some are. Translations need to be checked when the source subtitle file is updated.

### PR DESCRIPTION
**Pull request by egekorkan**
fixes #150 . They need to put into the YouTube subtitles after the merge

### CODE REVIEW

**Comment by egekorkan** [comment]
fixes #150 . They need to put into the YouTube subtitles after the merge

**Comment by egekorkan** [comment]
@ashimura can you have a look if the Japanese needs a fix as well and add it to this PR? 
@lmy441900  can you have a look if the Chinese needs a fix as well and add it to this PR?

**Comment by lmy441900** [comment]
The problem doesn't exist in the Simplified Chinese subtitles.

**Comment by egekorkan** [comment]
@chachamimm has checked the Japanese version in the meeting of 22.02. We are merging this but the changes need to be pushed to YouTube. @dontcallmedom can you update the English and French subtitles on YouTube?

**Comment by dontcallmedom** [comment]
fr and en youtube subtitles updated

**Comment by egekorkan** [comment]
Thank you! It looks good :)

**Pull request merged**
