### PR TITLE
Add eclipsecon 2021 video

### LINKED ISSUE #381: Add node-wot and editdor video
Just found this video from Eclipse:

https://www.youtube.com/watch?app=desktop&v=GljUcstf9mw

We should add it to our collection

### PR DESCRIPTION
**Pull request by egekorkan**
fixes #381 

[Preview](https://deploy-preview-385--wot-marketing.netlify.app/videos/) (video image not displayed)

### CODE REVIEW

**Review by danielpeintner — CHANGES_REQUESTED** [review]
I think we agreed on reverse chronological order. Hence more recent videos first.

EDIT: BTW, the source code speaks about 2020-09-17 while EclipseCon was 2021. Is this correct?

**Comment by egekorkan** [comment]
> Hence more recent videos first.

My bad, I will change. Which source code speaks about 2020?

**Comment by egekorkan** [comment]
@danielpeintner I got what you meant with source code date, I have fixed it.

I have moved the video up and also reformatted everything to use consistent space based indentation. Please hide white spaces to review

**Review by danielpeintner — APPROVED** [review]

**Comment by egekorkan** [comment]
Call of 21.03: merging since it is a minor thing

**Pull request merged**
