### PR TITLE
feat: add videos sub page

### PR DESCRIPTION
**Pull request by danielpeintner**
see https://github.com/w3c/wot-marketing/issues/123

### CODE REVIEW

**Comment by sebastiankb** [comment]
we should extend the videos with:

- [Industry of Things World USA 2016 Interview - Jeff Jaffe, W3C ](https://www.youtube.com/watch?list=PLEyJjfPQS2aCnJ7fktjgmnwvl_RmsvQbd&v=VKKxnk-aRhY&feature=youtu.be)
- [W3C meeting in Düsseldorf: Another step towards IoT standardization](https://www.youtube.com/watch?v=zGr6ZmeXjDM)
- [A common language for machines: new W3C consortium standard for IoT](https://www.youtube.com/watch?v=5k4JufTE9MQ)

**Comment by sebastiankb** [comment]
we can also link conference / plugfest talks such as
- [Auto-population using Node-RED Node Generator - TPAC 2020 Demo by Web of Things Groups](https://www.youtube.com/watch?v=oAcYbJ6P9bU)
- [W3C Web of Things Description for API Description of Devices](https://www.youtube.com/watch?v=ySLuAIoz0Dg)
- [W3C WoT PlugFest outcome: Sprinkler and Display sync](https://www.youtube.com/watch?v=JqKBwkvrjio)

**Comment by sebastiankb** [comment]
@danielpeintner will add the mentioned videos to the webpage after the merge

**Comment by danielpeintner** [comment]
see follow-up PR https://github.com/w3c/wot-marketing/pull/129

**Pull request merged**
